local datos = require("main.datos")

function init(self)
	self.to = go.get_position()
	self.to.y = -1000
	self.disparar = false
	msg.post("", "acquire_input_focus")
end


function update(self, dt)
	if self.disparar ~= false then
		datos.disparar_rayo(self, self.to)
	end
end



function on_input(self, action_id, action)
	if action_id == hash("ray2") and action.pressed then
		if self.disparar == true then
			self.disparar = false
		else 
			self.disparar = true
		end
	end
end
